function [A] = PendulumDAEJac(x,t,pend)
    m = pend.m;
    l = pend.l;
    ml = m*l;
    A = [ 0       , 1   , 0       ,   0   , 0       ; ...
          -x(5)/ml, 0   , 0       ,   0   , -x(1)/ml; ...
          0       , 0   , 0       ,   1   , 0       ; ...
          0       , 0   , -x(5)/ml,   0   , -x(3)/ml; ...
          2*x(1)  , 0   , 2*x(3)  ,   0   , 0        ];
end

